RELOAD = "location.reload()"
LIKERS_COUNT = "graphql.shortcode_media.edge_media_preview_like.count"
ADDITIONAL_DATA = "window.insta_data = window.__additionalData[Object.keys(window.__additionalData)[0]].data"
SHARED_DATA = "window.insta_data = window._sharedData.entry_data.PostPage[0]"
RETURN_DATA = "return ('graphql' in window.insta_data)"
CAPTION_1 = "return window.insta_data.graphql.shortcode_media.edge_media_to_caption.edges[0].node.text"
CAPTION_2 = "return window.insta_data.media.caption.text"
NUMBER_OF_POST = "graphql.user.edge_owner_to_timeline_media.count"
SCROLL_SCREEN = "window.scrollTo(0, document.body.scrollHeight);"
IS_PRIVATE = "graphql.user.is_private"
BASE_QUERY_1 = "return window.__additionalData[Object.keys(window.__additionalData)[0]].data."
BASE_QUERY_2 = "return window._sharedData.entry_data.ProfilePage[0]."
PROFILE_PIC = "graphql.user.profile_pic_url"
BUSINESS_ACCOUNT = "graphql.user.is_business_account"
BUSINESS_CATEGORY = "graphql.user.business_category_name"
BIOGRAPHY = "graphql.user.biography"
GET_SCROLL_HEIGHT = "return document.getElementsByTagName('main')[0].scrollHeight"
SCROLL_1000 = "window.scrollBy(0, 1000)"
FOLLOWERS_COUNT = "graphql.user.edge_followed_by.count"
FOLLOWING_COUNT = "graphql.user.edge_follow.count"
GET_TITLE_1 = "return document.title"
GET_TITLE_2 = "return document.getElementsByTagName('title')[0].text"
ACTIVITY_COUNT = "return window._sharedData.activity_counts"
VIEWER = "return window._sharedData.config.viewer"
POSSIBLE_POSTS = "return window._sharedData.entry_data.TagPage[0].graphql.hashtag.edge_hashtag_to_media.count"
SCROLL_TO_TOP = "window.scrollTo(0, 0);"
SCROLLED_TO_BOTTOM = "return window.scrollMaxY == window.scrollY"