# Generated by Django 3.1 on 2020-08-14 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_botsettings_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsettings',
            name='icerebrouser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_settings', to='app_main.icerebrouser'),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='instauser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_settings', to='app_main.instauser'),
        ),
    ]
