# Generated by Django 3.1 on 2020-08-15 13:36

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_auto_20200814_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsettings',
            name='bypass_security_challenge_using',
            field=models.IntegerField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], default=1),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='dont_skip_business_categories',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Advertising Agency', 'Advertising Agency'), ('Advertising/Marketing', 'Advertising/Marketing'), ('Art', 'Art'), ('Art Gallery', 'Art Gallery'), ('Art Museum', 'Art Museum'), ('Artist', 'Artist'), ('Arts & Entertainment', 'Arts & Entertainment'), ('Arts & Humanities Website', 'Arts & Humanities Website'), ('Athlete', 'Athlete'), ('Auto Dealers', 'Auto Dealers'), ('Business & Utility Services', 'Business & Utility Services'), ('Clothing Store', 'Clothing Store'), ('Community', 'Community'), ('Community Organization', 'Community Organization'), ('Company', 'Company'), ('Consulting Agency', 'Consulting Agency'), ('Content & Apps', 'Content & Apps'), ('Creators & Celebrities', 'Creators & Celebrities'), ('Education', 'Education'), ('Food & Personal Goods', 'Food & Personal Goods'), ('General Interest', 'General Interest'), ('Graphic Designer', 'Graphic Designer'), ('Home Goods Stores', 'Home Goods Stores'), ('Home Services', 'Home Services'), ('Jewelry/Watches', 'Jewelry/Watches'), ('Lifestyle Services', 'Lifestyle Services'), ('Local Business', 'Local Business'), ('Local Events', 'Local Events'), ('Management Service', 'Management Service'), ('Media/News Company', 'Media/News Company'), ('Non-Profits & Religious Organizations', 'Non-Profits & Religious Organizations'), ('Party Entertainment Service', 'Party Entertainment Service'), ('Personal Goods & General Merchandise Stores', 'Personal Goods & General Merchandise Stores'), ('Photographer', 'Photographer'), ('Photography Videography', 'Photography Videography'), ('Product/Service', 'Product/Service'), ('Professional Service', 'Professional Service'), ('Professional Sports Team', 'Professional Sports Team'), ('Public Figure', 'Public Figure'), ('Public Relations Agency', 'Public Relations Agency'), ('Publishers', 'Publishers'), ('Restaurants', 'Restaurants'), ('Ski Resort', 'Ski Resort'), ('Sport', 'Sport'), ('Sports & Recreation', 'Sports & Recreation'), ('Transportation & Accomodation Services', 'Transportation & Accomodation Services'), ('Travel Agency', 'Travel Agency'), ('Wine/Spirits', 'Wine/Spirits')], max_length=854, null=True),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='mandatory_character',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LATIN', 'Latin'), ('GREEK', 'Greek'), ('CYRILLIC', 'CYRILLIC'), ('ARABIC', 'Arabic'), ('HEBREW', 'Hebrew'), ('CJK', 'CJK'), ('HANGUL', 'Hangul'), ('HIRAGANA', 'Hiragana'), ('KATAKANA', 'Katakana'), ('THAI', 'Thai'), ('MATHEMATICAL', 'Mathematical')], max_length=81, null=True),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='qs_sleep_after',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('like', 'like'), ('comment', 'comment'), ('follow', 'follow'), ('unfollow', 'unfollow'), ('server_call', 'server_call')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='skip_business_categories',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Advertising Agency', 'Advertising Agency'), ('Advertising/Marketing', 'Advertising/Marketing'), ('Art', 'Art'), ('Art Gallery', 'Art Gallery'), ('Art Museum', 'Art Museum'), ('Artist', 'Artist'), ('Arts & Entertainment', 'Arts & Entertainment'), ('Arts & Humanities Website', 'Arts & Humanities Website'), ('Athlete', 'Athlete'), ('Auto Dealers', 'Auto Dealers'), ('Business & Utility Services', 'Business & Utility Services'), ('Clothing Store', 'Clothing Store'), ('Community', 'Community'), ('Community Organization', 'Community Organization'), ('Company', 'Company'), ('Consulting Agency', 'Consulting Agency'), ('Content & Apps', 'Content & Apps'), ('Creators & Celebrities', 'Creators & Celebrities'), ('Education', 'Education'), ('Food & Personal Goods', 'Food & Personal Goods'), ('General Interest', 'General Interest'), ('Graphic Designer', 'Graphic Designer'), ('Home Goods Stores', 'Home Goods Stores'), ('Home Services', 'Home Services'), ('Jewelry/Watches', 'Jewelry/Watches'), ('Lifestyle Services', 'Lifestyle Services'), ('Local Business', 'Local Business'), ('Local Events', 'Local Events'), ('Management Service', 'Management Service'), ('Media/News Company', 'Media/News Company'), ('Non-Profits & Religious Organizations', 'Non-Profits & Religious Organizations'), ('Party Entertainment Service', 'Party Entertainment Service'), ('Personal Goods & General Merchandise Stores', 'Personal Goods & General Merchandise Stores'), ('Photographer', 'Photographer'), ('Photography Videography', 'Photography Videography'), ('Product/Service', 'Product/Service'), ('Professional Service', 'Professional Service'), ('Professional Sports Team', 'Professional Sports Team'), ('Public Figure', 'Public Figure'), ('Public Relations Agency', 'Public Relations Agency'), ('Publishers', 'Publishers'), ('Restaurants', 'Restaurants'), ('Ski Resort', 'Ski Resort'), ('Sport', 'Sport'), ('Sports & Recreation', 'Sports & Recreation'), ('Transportation & Accomodation Services', 'Transportation & Accomodation Services'), ('Travel Agency', 'Travel Agency'), ('Wine/Spirits', 'Wine/Spirits')], max_length=854, null=True),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='user_interact_media',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PHOTO', 'Photos'), ('CAROUSEL', 'Carousel'), ('VIDEO', 'Videos')], default='1,2,3', max_length=20, null=True),
        ),
    ]
