# Generated by Django 3.1 on 2020-08-15 14:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_auto_20200815_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsettings',
            name='bypass_security_challenge_using',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], default='EMAIL', max_length=5),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='mandatory_character',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LATIN', 'Latin'), ('GREEK', 'Greek'), ('CYRILLIC', 'Cyrillic'), ('ARABIC', 'Arabic'), ('HEBREW', 'Hebrew'), ('CJK', 'CJK'), ('HANGUL', 'Hangul'), ('HIRAGANA', 'Hiragana'), ('KATAKANA', 'Katakana'), ('THAI', 'Thai'), ('MATHEMATICAL', 'Mathematical')], max_length=81, null=True),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='proxy_address',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='proxy_port',
            field=models.TextField(blank=True, max_length=5),
        ),
    ]
