# Generated by Django 3.1 on 2020-08-26 19:56

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_botrunsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='botrunsettings',
            name='repeat_action_if_ended_before_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='botrunsettings',
            name='follow_by_list_settings_usernames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='botrunsettings',
            name='like_by_users_settings_usernames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='botrunsettings',
            name='unfollow_users_settings_boundary_to_check',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
