# Generated by Django 3.1 on 2020-09-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0008_auto_20200826_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botrunsettings',
            name='follow_user_follow_settings_what',
            field=models.CharField(choices=[('followers', 'Followers'), ('following', 'Following')], default='followers', max_length=20),
        ),
    ]
