# Generated by Django 3.1 on 2020-09-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0009_auto_20200904_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsettings',
            name='proxy_port',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
