# Generated by Django 3.1 on 2020-10-02 17:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0010_auto_20200904_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_reserved', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now_add=True)),
                ('host', models.CharField(max_length=15)),
                ('port', models.IntegerField(validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proxy', to='app_main.icerebrouser')),
            ],
            options={
                'db_table': 'Port',
                'unique_together': {('host', 'port')},
            },
        ),
    ]
