# Generated by Django 3.1 on 2020-10-05 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0011_proxyaddress'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proxyaddress',
            table='proxy_address',
        ),
    ]
