# Generated by Django 3.1 on 2020-10-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0013_auto_20201005_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='proxy_address',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='proxy_port',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
